const hourEl = document.querySelector('.hour')
const minuteEl = document.querySelector('.minute')
const secondEl = document.querySelector('.second')
const timeEl = document.querySelector('.time')
const dataEl = document.querySelector('.date')
const toggl = document.querySelector('.toggle')
